dist: bionic

script:
  - sudo ./travis-build.sh

branches:
  only:
    - master
    - development
    - legacy

deploy:
  - provider: script
    script: wget -qO - https://git.io/JJEvt | sh -s package/*.deb
    skip_cleanup: true

notifications:
  email: false
